/* eslint-disable */
/**
 * Generated by convex dev.
 * Stub for local builds without convex dev running.
 */

import type { FilterApi, FunctionReference } from "convex/server";

export const api: PublicApiType = {} as any;
export const internal: InternalApiType = {} as any;

export type PublicApiType = FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export type InternalApiType = FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

declare const fullApi: any;
